services:
  postgres:
    image: postgres:16.1-alpine3.19
    hostname: postgres.shooper.nmb
    container_name: postgres.shooper.nmb
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres}
    volumes:
      - .volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    image: shooper.nmb
    hostname: server.shooper.nmb
    container_name: server.shooper.nmb
    tty: true
    restart: always
    depends_on:
      - postgres
    ports:
      - ${BACKEND_PORT:-8080}:${BACKEND_PORT:-8080}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    command: ["node", "apps/server/dist/main.js"]

  web:
    image: shooper.nmb
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
    hostname: web.shooper.nmb
    container_name: web.shooper.nmb
    tty: true
    restart: always
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    command: ["node", "apps/web/server.js"]
