services:
  postgres:
    image: postgres:16.1-alpine3.19
    hostname: postgres
    container_name: postgres
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    image: shooper.nmb
    hostname: server.shooper.nmb
    container_name: server.shooper.nmb
    tty: true
    restart: always
    depends_on:
      - postgres
    ports:
      - ${BACKEND_PORT:-80}:${BACKEND_PORT:-80}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    command: ["node", "apps/server/dist/main.js"]

  web:
    image: shooper.nmb
    hostname: web.shooper.nmb
    container_name: web.shooper.nmb
    tty: true
    restart: always
    ports:
      - ${FRONTEND_PORT:-8080}:${FRONTEND_PORT:-8080}
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
    command: ["node", "apps/web/server.js"]
